# -*- coding: utf-8 -*-
# Part of WhatsApp Business Cloud API Enterprise Suite.
# License: OPL-1.

import re
import logging
from odoo import models, fields, api, _
from odoo.exceptions import UserError

_logger = logging.getLogger(__name__)


class WhatsAppTemplate(models.Model):
    _name = 'whatsapp.template'
    _description = 'Meta WhatsApp Message Template'
    _inherit = ['mail.thread']
    _order = 'name, id desc'

    name = fields.Char(
        string='Template Name',
        required=True,
        tracking=True,
        help='Internal identifier and Meta template identifier (must match Meta approved name).'
    )
    account_id = fields.Many2one(
        'whatsapp.account',
        string='WhatsApp Account',
        required=True,
        ondelete='cascade',
        tracking=True
    )
    company_id = fields.Many2one(
        'res.company',
        string='Company',
        related='account_id.company_id',
        store=True,
        readonly=True
    )
    meta_template_id = fields.Char(
        string='Meta Template ID',
        index=True,
        help='Unique ID generated by Meta upon template creation.'
    )
    language_code = fields.Char(
        string='Language Code',
        default='en_US',
        required=True,
        help='ISO language code (e.g. en_US, ar, ur, es, fr).'
    )
    category = fields.Selection(
        [
            ('UTILITY', 'Utility'),
            ('MARKETING', 'Marketing'),
            ('AUTHENTICATION', 'Authentication'),
        ],
        string='Category',
        default='UTILITY',
        required=True
    )
    state = fields.Selection(
        [
            ('draft', 'Draft'),
            ('pending', 'Pending Approval'),
            ('approved', 'Approved'),
            ('rejected', 'Rejected'),
            ('paused', 'Paused'),
        ],
        string='Meta Status',
        default='approved',
        tracking=True
    )

    # Model Binding for dynamic variables
    model_id = fields.Many2one(
        'ir.model',
        string='Applies to Model',
        help='Odoo model for which this template renders dynamic variables (e.g. Sale Order, Invoice).'
    )
    model = fields.Char(
        string='Model Technical Name',
        related='model_id.model',
        store=True,
        readonly=True
    )

    # Template Content Components
    header_type = fields.Selection(
        [
            ('none', 'None'),
            ('text', 'Text'),
            ('document', 'Document (PDF)'),
            ('image', 'Image'),
            ('video', 'Video'),
        ],
        string='Header Format',
        default='none'
    )
    header_text = fields.Char(string='Header Text')
    body_text = fields.Text(
        string='Body Text',
        required=True,
        help='Template body text with variables like {{1}}, {{2}} or dynamic expressions like {{object.name}}.'
    )
    footer_text = fields.Char(string='Footer Text')

    # Variable Mapping: comma-separated field expressions corresponding to {{1}}, {{2}}, etc.
    variable_mapping = fields.Char(
        string='Body Variables (CSV)',
        help='Comma-separated field expressions matching {{1}}, {{2}} in order. Example: partner_id.name, name, amount_total'
    )

    button_ids = fields.One2many(
        'whatsapp.template.button',
        'template_id',
        string='Interactive Buttons'
    )

    def _evaluate_field_path(self, record, field_path):
        """Safely traverse dotted field path on record, e.g., 'partner_id.name'."""
        try:
            curr = record
            for part in field_path.strip().split('.'):
                if not curr:
                    return ''
                curr = getattr(curr, part, '')
            if isinstance(curr, fields.Monetary) or isinstance(curr, float):
                return f"{curr:,.2f}"
            return str(curr or '')
        except Exception as e:
            _logger.warning("Error evaluating field path %s on %s: %s", field_path, record, str(e))
            return ''

    def render_components(self, record=None, custom_header_url=None):
        """
        Constructs the Meta Cloud API 'components' payload for sending template messages.
        Replaces variables {{1}}, {{2}} based on variable_mapping or direct record evaluation.
        """
        self.ensure_one()
        components = []

        # 1. Header Component
        if self.header_type in ['document', 'image', 'video'] and custom_header_url:
            components.append({
                "type": "header",
                "parameters": [{
                    "type": self.header_type,
                    self.header_type: {
                        "link": custom_header_url
                    }
                }]
            })
        elif self.header_type == 'text' and self.header_text and record:
            # Check for header variable
            components.append({
                "type": "header",
                "parameters": [{
                    "type": "text",
                    "text": str(record.display_name or record.name)
                }]
            })

        # 2. Body Component
        if self.body_text and record:
            parameters = []
            if self.variable_mapping:
                field_list = [f.strip() for f in self.variable_mapping.split(',') if f.strip()]
                for f_path in field_list:
                    val = self._evaluate_field_path(record, f_path)
                    parameters.append({
                        "type": "text",
                        "text": str(val or '-')
                    })
            else:
                # Detect {{1}}, {{2}} in body_text and provide default values
                matches = re.findall(r'\{\{(\d+)\}\}', self.body_text)
                for _ in matches:
                    parameters.append({
                        "type": "text",
                        "text": str(record.display_name or record.name)
                    })

            if parameters:
                components.append({
                    "type": "body",
                    "parameters": parameters
                })

        return components

    def render_preview_text(self, record=None):
        """Generates human-readable preview of the template."""
        self.ensure_one()
        rendered_body = self.body_text or ''
        if record and self.variable_mapping:
            field_list = [f.strip() for f in self.variable_mapping.split(',') if f.strip()]
            for idx, f_path in enumerate(field_list, start=1):
                val = self._evaluate_field_path(record, f_path)
                rendered_body = rendered_body.replace(f"{{{{{idx}}}}}", str(val or ''))
        return rendered_body


class WhatsAppTemplateButton(models.Model):
    _name = 'whatsapp.template.button'
    _description = 'Interactive Button for WhatsApp Template'
    _order = 'sequence, id'

    template_id = fields.Many2one(
        'whatsapp.template',
        string='Template',
        required=True,
        ondelete='cascade'
    )
    sequence = fields.Integer(string='Sequence', default=10)
    name = fields.Char(string='Button Label', required=True)
    button_type = fields.Selection(
        [
            ('quick_reply', 'Quick Reply'),
            ('url', 'Call to Action URL'),
            ('phone_number', 'Call Phone Number'),
        ],
        string='Button Type',
        default='quick_reply',
        required=True
    )
    url = fields.Char(string='Target URL')
    phone_number = fields.Char(string='Target Phone Number')
